- name: main | add vars
  include_vars: "{{ ansible_os_family }}.yml"

- include: compatibility.yml

- include: hhvm.yml

- include: apache.yml
  when: apache is defined and apache.install == 1

- include: nginx.yml
  when: nginx is defined and nginx.install == 1
