- name: dotfiles | set facts
  set_fact: >
    dotfiles_path="{{ '/home/vagrant' if protobox_env == 'vagrant' else '/home/' ~ ansible_user_id }}"

- name: dotfiles | install dotfiles
  git: >
    repo={{ item.repo }}
    dest={{ item.path|default(dotfiles_path) }}
  with_items: server.dotfiles.git
  when: server.dotfiles.git is defined

# check for vimrc if we are not in the root folder to symlink
#- name: dotfiles | check for vimrc
#  stat: >
#    path={{ item.path|default(dotfiles_path) }}/.vimrc
#  with_items: server.dotfiles.git
#  register: dotfiles_vimrc
#  when: server.dotfiles.git is defined and item.path|default(dotfiles_path) != dotfiles_path

#- debug: var=dotfiles_vimrc

#- debug: var=item.stat.exists
#  with_items: dotfiles_vimrc.results

#- debug: msg="{{ item.stat.exists }} - {{ item.item.path }} - {{ dotfiles_path }}"
#  with_items: dotfiles_vimrc.results

# add the symlink from previous step
#- name: dotfiles | create .vimrc symlink
#  file: >
#    src={{ item.item.path }}/.vimrc
#    dest={{ dotfiles_path }}/.vimrc
#    state=symlink
#  with_items: dotfiles_vimrc.results
#  when: item.stat.exists and item.item.path != dotfiles_path + '/.vimrc'

- name: dotfiles | copy dot files
  command: >
    cp {{ item }} {{ dotfiles_path }}/{{ item|basename }}
  with_fileglob: /vagrant/data/dot/*
  sudo: yes
  when: protobox_env == 'vagrant' and item|basename != '.gitignore'
