- name: compatibility | require php
  fail: msg="PHP is required"
  when: php is not defined or php.install != 1

- name: compatibility | require apache or nginx
  fail: msg="Apache or Nginx is required"
  when: (apache is not defined or apache.install != 1) and (nginx is not defined or nginx.install != 1)

- name: compatibility | require mysql
  fail: msg="Mysql is required"
  when: mysql is not defined or mysql.install != 1

- name: compatibility | check for install path
  fail: msg="Install path missing"
  with_items: applications.wordpress
  when: item.path is not defined

- name: compatibility | check for options
  fail: msg="Wordpress - Options are missing"
  with_items: applications.wordpress
  when: item.options is not defined

- name: compatibility | check for wordpress version
  fail: msg="Wordpress - Version is required"
  with_items: applications.wordpress
  when: item.options.version is not defined or item.options.version == ''

- name: compatibility | check for settings
  fail: msg="Wordpress - Settings are missing"
  with_items: applications.wordpress
  when: item.settings is not defined
