- name: main | ensure ntpd is at the latest version
  apt: pkg=ntp state=latest
  notify:
    - ntpd-restart

- name: main | install dependencies
  apt: >
    pkg={{ item }} 
    state=latest
  with_items:
    - git-core
  sudo: yes

#- name: Copy the EPEL repository definition
#  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

#- name: Create the GPG key for EPEL
#  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

#- name: Set up iptables rules
#  copy: src=iptables-save dest=/etc/sysconfig/iptables
#  notify: restart iptables