- name: debian | get the key
  apt_key: >
    url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    id=rabbitmq-signing-key-public
    state=present
  sudo: yes

- name: debian | add the repository
  copy: >
    content="deb http://www.rabbitmq.com/debian/ {{ rabbitmq.release|default('stable') }} main" 
    dest=/etc/apt/sources.list.d/rabbitmq.list
  sudo: yes
  register: rabbitmq_repo

- name: debian | updates apt cache
  apt: update_cache=yes
  sudo: yes
  when: rabbitmq_repo.changed

- name: debian | install it
  apt: >
    pkg=rabbitmq-server
    state=latest
  sudo: yes
