- name: rpm | add key
  rpm_key: > 
    key=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    state=present
  sudo: yes

- name: rpm | install
  yum: > 
    name=rabbitmq-server-3.2.2-1.noarch.rpm
    state=present
  sudo: yes
