- name: Applications
  hosts: all
  vars_files:
    - [ $protobox_config ]
  roles:
    - { role: 'repository', dir: 'applications/repository', when: "applications.repository is defined" }
    - { role: 'lemonstand', dir: 'applications/lemonstand', when: "applications.lemonstand is defined" }
    - { role: 'wordpress', dir: 'applications/wordpress', when: "applications.wordpress is defined" }
    - { role: 'laravel', dir: 'applications/laravel', when: "applications.laravel is defined" }
