- name: main | installs dependencies
  apt: >
    pkg={{ item }} 
    state=latest
    update_cache=yes
  with_items:
    - python-mysqldb
  sudo: yes

- name: main | installs mysql packages
  apt: >
    pkg={{ item }} 
    state=latest
  with_items:
    - mysql-server
  sudo: yes
  notify: 
    - mysql-start

#- name: install support packages
#  apt: >
#    pkg={{ item }} 
#    state=installed
#  with_items:
#    - mytop
#    - mysqltuner

#- name: insert iptables rule
#  lineinfile: >
#    dest=/etc/sysconfig/iptables 
#    state=present 
#    regexp="{{ mysql_port }}"
#    insertafter="^:OUTPUT " 
#    line="-A INPUT -p tcp  --dport {{ mysql_port }} -j  ACCEPT"
#  notify: restart iptables

- name: main | create mysql configuration file
  template: >
    src=my.cnf.j2
    dest=/etc/mysql/my.cnf
    owner=root
    group=root
    mode=0644
  sudo: yes
  notify:
    - mysql-restart

#- name: main | remove root user from hosts
#  mysql_user: >
#    name=root
#    host={{ item }}
#    state=absent
#  with_items:
#    - ansible_hostname
#    - ansible_fqdn
#    - 127.0.0.1
#    - ::1
#    #- localhost

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: main | update root password for all hosts
  mysql_user: >
    name=root
    host={{ item }}
    password={{ mysql.root_password|default('') }}
  with_items:
    - ansible_hostname
    - 127.0.0.1
    - ::1
    - localhost

- name: main | add root credentials
  template: >
    src=my.user.cnf.j2
    dest=/root/.my.cnf
    owner=root
    mode=0600
  sudo: yes
  when: ansible_user_id == 'root'
  notify:
    - mysql-restart

# TODO : Temp to get vagrant my.cnf file in
- name: main | add user credentials
  template: >
    src=my.user.cnf.j2
    dest=/home/{{ item }}/.my.cnf
    owner={{ item }}
    mode=0600
  sudo: yes
  with_items:
    #- ansible_user_id
    - vagrant
  notify:
    - mysql-restart

- name: main | remove anonymous user
  mysql_user: >
    name=''
    host={{ item }}
    state=absent
  with_items:
    - localhost
    - ansible_fqdn

- name: main | remove the test database
  mysql_db: >
    name=test 
    state=absent

# TODO : priv={{ item.name }}:{{ item.grant }}
# priv=*.*:ALL host='%'
- name: main | install all users
  mysql_user: >
    name={{ item.user }}
    password={{ item.password }}
    priv=*.*:{{ item.grant|join(',') }}
    state=present
  with_items: mysql.databases
  when: mysql.databases is defined

- name: main | create mysql databases
  mysql_db: >
    name={{ item.name }}
    state=present
  with_items: mysql.databases
  when: mysql.databases is defined

# TODO : temp path to vagrant folder
- name: main | check for mysql files
  stat: >
    path=/vagrant/data/sql/{{ item.name }}.sql
  register: mysql_import_db
  with_items: mysql.databases
  when: mysql.databases is defined

# TODO : switch target location to use register path from above
- name: main | import stored mysql databases
  mysql_db: >
    name={{ item.0.name }}
    target=/vagrant/data/sql/{{ item.0.name }}.sql
    state=import
  with_together: 
    - mysql.databases
    - mysql_import_db.results
  when: mysql.databases is defined and item.1.stat.exists

- name: main | import custom mysql databases
  mysql_db: >
    name={{ item.name }}
    target={{ item.sql_file|default('') }}
    state=import
  with_items: mysql.databases
  when: mysql.databases is defined and item.sql_file is defined and item.sql_file != ''
