- name: pear | install pear packages
  apt: >
    pkg={{ item }} 
    state=installed
  with_items:
    - php5-dev
    - php-pear

- name: pear | update pear packages
  command: pear upgrade

- name: pear | set pear auto-discover
  command: pear config-set auto_discover 1

# this fails often (dns problems, pear problems, etc. So just ignore the errors and continue.)
#- name: pear | pear install the PHP QA Toolchain
#  command: pear install pear.phpqatools.org/phpqatools creates=/usr/bin/phpunit
#  ignore_errors: True