
# Debian / Ubuntu

#- name: version | add dotdeb package for php 5.4
#  apt_repository: >
#    repo='deb http://packages.dotdeb.org {{ ansible_lsb.codename }}-php54 all' 
#    state=present
#  sudo: yes
#  when: ansible_os_family == 'Debian' and php.version == '54'

#- name: version | add dotdeb package sources for php 5.4
#  apt_repository: >
#    repo='deb-src http://packages.dotdeb.org {{ ansible_lsb.codename }}-php54 all' 
#    state=present
#  sudo: yes
#  when: ansible_os_family == 'Debian' and php.version == '54'

#- name: version | add dotdeb apt key for php 5.4
#  apt_key: >
#    url=http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x7E3F070089DF5277 
#    state=present
#  sudo: yes
#  when: ansible_os_family == 'Debian' and php.version == '54'

- name: version | add php 5.4 repository
  apt_repository: repo=ppa:ondrej/php5-oldstable
  sudo: yes
  when: ansible_os_family == 'Debian' and php.version == '54'

- name: version | updates apt cache
  apt: update_cache=true
  sudo: yes
  when: ansible_os_family == 'Debian' and php.version == '54'

# php

- name: version | install php
  apt: >
    pkg={{ item }} 
    state=latest
    force=yes
  with_items:
    - php5
  sudo: yes

# modules

- name: main | install php packages
  apt: >
    pkg={{ item }}
    state=latest
  with_items: php.modules
  sudo: yes
  when: php.modules is defined

# backup php.ini

#- name: main | make backup of php.ini
#  sudo: yes
#  copy: >
#    src=/etc/php5/apache2/php.ini 
#    dest=/etc/php5/apache2/php.ini.bak
#    force=yes
