- name: mariadb-restart
  service: >
    name=mysql
    state=restarted
  sudo: yes

- name: mariadb-start
  service: >
    name=mysql 
    state=started
    enabled=true
  sudo: yes

- name: mariadb-stop
  service: >
    name=mysql 
    state=stopped
  sudo: yes
