- name: rabbitmq-restart
  service: >
    name=rabbitmq-server 
    state=restarted
  sudo: yes

- name: rabbitmq-start
  service: >
    name=rabbitmq-server 
    state=started
  sudo: yes

- name: rabbitmq-stop
  service: >
    name=rabbitmq-server 
    state=stopped
  sudo: yes
