# TODO : check for apache: 'which apache2' before uninstall

# TODO : this code will work when 
# https://github.com/ansible/ansible/issues/5180
# is fixed
#- name: main | uninstall apache packages
#  apt: >
#    pkg={{ item }} 
#    state=absent
#    purge=yes
#    force=yes
#  with_items:
#    - apache2*
#  sudo: yes

#apt-get remove -y apache.* 
- name: main | uninstall apache packages
  command: apt-get purge -y apache2* libapache2*
  sudo: yes

- name: main | installs nginx packages
  apt: >
    pkg={{ item }} 
    state=latest
  with_items:
    - nginx
  sudo: yes
  notify:
    - nginx-start

- name: main | updates apt cache
  apt: update_cache=true
  sudo: yes

- name: main | deactivates the default virtualhost
  command: >
    rm -rf /etc/nginx/sites-available/default && rm -rf /etc/nginx/sites-enabled/default
  sudo: yes
  notify:
    - nginx-restart

- name: main | add nginx configurations
  template: >
    src={{ item.template|default('default.conf.j2') }}
    dest=/etc/nginx/sites-available/{{ item.name }}
    mode=0640
  with_items: nginx.vhosts
  sudo: yes
  notify:
    - nginx-restart

- name: main | enable the virtualhost
  file: >
    src=/etc/nginx/sites-available/{{ item.name }}
    dest=/etc/nginx/sites-enabled/{{ item.name }}
    state=link
  with_items: nginx.vhosts
  sudo: yes
  notify:
    - nginx-restart
