---

- name: Core
  hosts: all
  vars_files:
    - "../data/config/common.yml"
  roles:
    # Common functionality
    - { role: 'common' }

    # Server handling
    - { role: 'server', when: "server is defined" }

    # Database handling
    - { role: 'mysql', when: "mysql is defined and mysql.install == 1" }
    #- { role: 'postgres', when: "postgres is defined and postgres.install == 1" }
    #- { role: 'mongodb', when: "mongodb is defined and mongodb.install == 1" }
    #- { role: 'redis', when: "redis is defined and redis.install == 1" }

    # Web servers
    - { role: php, when: "php is defined and php.install == 1" }
    - { role: apache, when: "apache is defined and apache.install == 1" }
    - { role: nginx, when: "nginx is defined and nginx.install == 1" }
    - { role: node, when: "node is defined and node.install == 1" }

    # Workers
    #- { role: 'beanstalkd', when: "beanstalkd is defined and beanstalkd.install == 1" }

    # Dev tools
    - { role: 'localtunnel', when: "localtunnel is defined and localtunnel.install == 1" }

- include: applications/apps.yml
  when: applications is defined and applications.install == 1
