- name: hhvm-restart
  service: >
    name=hhvm 
    state=restarted
  sudo: yes

- name: hhvm-start
  service: >
    name=hhvm 
    state=started
  sudo: yes

- name: hhvm-stop
  service: >
    name=hhvm 
    state=restarted
  sudo: yes

- name: apache-restart
  service: >
    name=apache2 
    state=restarted
  sudo: yes